// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gfs_FsAkMgEqx2-lziwzkI89r6wklnU',
    appId: '1:845502919168:web:1be96382e3a77afc961ee5',
    messagingSenderId: '845502919168',
    projectId: 'fitness-life-7f19b',
    authDomain: 'fitness-life-7f19b.firebaseapp.com',
    storageBucket: 'fitness-life-7f19b.firebasestorage.app',
    measurementId: 'G-YTG8LNKTFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SWUTx3YQkHrccRoaObEik98-Sg1XOHQ',
    appId: '1:845502919168:android:592d9d449c5e3c8b961ee5',
    messagingSenderId: '845502919168',
    projectId: 'fitness-life-7f19b',
    storageBucket: 'fitness-life-7f19b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_LfD9Bs-pDnXiQRmYNdLBMeUpxzvHa8',
    appId: '1:845502919168:ios:c029cd23e5801cc3961ee5',
    messagingSenderId: '845502919168',
    projectId: 'fitness-life-7f19b',
    storageBucket: 'fitness-life-7f19b.firebasestorage.app',
    iosBundleId: 'com.fitnessislife.app',
  );

}
